CREATE TABLE Usuarios (
ID INT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR(255) NOT NULL,
Login VARCHAR(255) NOT NULL UNIQUE,
Senha VARCHAR(255) NOT NULL
);


CREATE TABLE Enderecos (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Cep NVARCHAR(10) NOT NULL,
	Logradouro NVARCHAR(255) NOT NULL,
	Complemento NVARCHAR(255) NULL,
	Bairro NVARCHAR(255) NOT NULL,
	Cidade NVARCHAR(255) NOT NULL,
	Uf NVARCHAR(2) NOT NULL,
	Numero NVARCHAR(10) NOT NULL,
	UsuarioId INT NOT NULL,
	CONSTRAINT FK_Enderecos_Usuarios FOREIGN KEY (UsuarioId) REFERENCES Usuarios(ID) ON DELETE CASCADE

);